### ISSUE TITLE
Missing empty line at the end of source files

### ISSUE THREAD

**Issue by 4parthy** [makevs/compse140#1]
POSIX standard defines a line as follows
> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

So, without an empty line at the end of a file, the last line is in fact an incomplete line, which in turn makes your file an incomplete file.

Just kidding, while there are [good reasons](https://stackoverflow.com/q/729692) to have an empty line at the end of text files, it does not matter as much for modern languages and editors, so you do you.

<details><summary></summary>
<p>
there was some very f-ed up copy pasta here lole
</p>
</details>

**Comment by makevs** [comment]
The code was already submitted for grading and will not be changed moving forward.
